### ISSUE TITLE
Letterboxd ratings getting cut in half

### ISSUE THREAD

**Issue by zdgro** [primetime43/Ratings-To-Plex-Ratings#5]
Hi there! 

Thanks so much for this easy to use tool, the idea of re-rating thousands of movies I've already rated on Letterboxd was a daunting task. 

The issue I'm having is the letterboxd ratings are getting halved when I import them to plex. (5/5 rating is showing as 2.5/5) 
I assume this is because the IMDB ratings would need to be halved to fit into the 5 star structure on plex.

I tried a couple more times to make sure that I have the letterboxd option checked, but still getting the same result.

Hopefully I'm not just making a dumb mistake I didn't think of...

**Comment by zdgro** [comment]
FYI my interim solution was to edit my ratings.csv to double the number for each entry.

**Comment by primetime43** [comment]
@zdgro okay ill look into it; I'm probably having the letterboxd rating and its already out of 5, unlike imdb. Thanks for letting me know.

**Comment by primetime43** [comment]
Fixed the issue by multiplying the letterboxd rating by 2. It appears the rating function that is used expects a number out of 10 and halves it itself.
