### ISSUE TITLE
Import Ratings from Letterboxd not work correctly

### ISSUE THREAD

**Issue by TtVrac** [primetime43/Ratings-To-Plex-Ratings#6]
![image](https://github.com/primetime43/Ratings-To-Plex-Ratings/assets/63391332/cb8bc13e-ad48-4e4f-b25f-2d20dbd413fc)

Hello, thank you for this superb project. I use it to import my Letterboxd notes, it works well for all whole number notes (1;2;3;4;5) but does not work with half numbers .5 (0.5;1.5;2.5;3.5; 4.5), is it just me?

**Comment by primetime43** [comment]
@TtVrac okay yea its probably an issue with the code. I didn't know letterboxd ratings did halfs. I'll look into it and get it fixed, thanks for brining this to my attention.

**Comment by TtVrac** [comment]
First time I use python but I think, I fixed the bug:
I change "int" into "float"
line 127                     your_rating = float(rating_str)*2

**Comment by primetime43** [comment]
> First time I use python but I think, I fixed the bug: I change "int" into "float" line 127 your_rating = float(rating_str)*2

yea that's what I figured the fix would be, just haven't had the change to do it yet. Thanks.

**Comment by primetime43** [comment]
Fixed in v1.2.2
